### ISSUE TITLE
Suggestion: Remove Lodash dependencies from the production build

### ISSUE THREAD

**Issue by SirLamer** [yury-dymov/redux-object#10]
I don't think the Lodash methods used in the package are really required. They have ES6 equivalents. Removing Lodash as a production dependency would be nice.

It is used very deliberately in the unit testing, so it should still be retained as a development dependency.

If you agree, I will implement, test and submit a PR after you publish the previous PR, but I am just checking that you agree first before committing time to it.

**Comment by yury-dymov** [comment]
I don't mind

**Comment by yury-dymov** [comment]
Closed via https://github.com/yury-dymov/redux-object/pull/12
