### ISSUE TITLE
Accessing related object not in the store

### ISSUE THREAD

**Issue by JakeDluhy** [yury-dymov/redux-object#18]
If I have `users` that have many `books`, and I make a request for a `user` object _without_ sideloading the related books, then I might have the following structure in my store:
```js
{
    users: {
        '1': {
            id: '1',
            type: 'users',
            attributes: {},
            relationships: {
                books: {
                    data: {
                        [{
                            id: '1',
                            type: 'books'
                        }, {
                            id: '2',
                            type: 'books'
                        }]
                    }
                }
            }
        }
    },
    books: {}
}
```

If I run `const user = build(state.entities, 'users', '1')` then I get the user back. However if I then run `user.books` I get `[null, null]`. I would expect that I should get 
```js
[{
    id: '1',
    type: 'books'
}, {
    id: '2',
    type: 'books'
}]
```

I have experienced many use cases where I don't need the full related object, just the id (to provide a link to that object, for instance) and so I won't `include` the related resources.

I'd be happy to make the changes if you would accept a PR!

**Comment by yury-dymov** [comment]
Hey @JakeDluhy,

it is supposed to normalize data first before saving in store. Have a look at https://github.com/yury-dymov/json-api-normalizer

**Comment by JakeDluhy** [comment]
Right, I'm using the `json-api-normalizer`. I misrepresented what my store looks like. I suppose it's more like
```js
{
    users: {
        '1': {
            id: '1',
            attributes: {},
            relationships: {
                books: {
                    data: {
                        [{
                            id: '1',
                            type: 'books'
                        }, {
                            id: '2',
                            type: 'books'
                        }]
                    }
                }
            }
        }
    },
    books: {}
}
```

My point is that if I've just made a request like `GET /users/1`, not `GET /users/1?include=books` then I won't have any books loaded into the store. Which means that when I do `user.books` it's going to return `[null, null]` (because it's trying to find the related resource and is unable to do so). I think that if it can't find the related resource, it should fall back to providing the relationship object, i.e.
```js
{ id: '1', type: 'books' }
```

**Comment by JakeDluhy** [comment]
Here's the diff of my changes: https://github.com/JakeDluhy/redux-object/commit/aa76ec01962bd9c1487167fde9a4a9a76777a919

**Comment by yury-dymov** [comment]
oh, now I see. Yeah, feel free to submit PR, I am happy to merge it

**Comment by JakeDluhy** [comment]
Thanks! Btw, I'm loving this library (and `json-api-normalizer`). It's really cleaning up our implementation of JSON API!

**Comment by yury-dymov** [comment]
Thank you for your contribution and kind words :)
