### ISSUE TITLE
Should not return empty array for relationships without data

### ISSUE THREAD

**Issue by gnapse** [yury-dymov/redux-object#20]
Why does `build` return an empty array for relationships that have no `data`? It makes it impossible to determine from a built object if the relationship data was present and indeed empty, versus when the relationship data was not present at all.

I think [this line](https://github.com/yury-dymov/redux-object/blob/0ecd873b76f2897cad108899173423a1907b280d/src/redux-object.js#L26) should return either `null` or `undefined`, perhaps most preferably the latter.

**Update:**

To be more precise, this only occurs when the relationship has `links` and no `data`, and `ignoreLinks: true` is given in the options. In this case, the error is not thrown, but the `buildRelationship` function returns `[]`. I think the fix should be to return `undefined` if the error is not thrown. I can make a PR for this case.

**Comment by yury-dymov** [comment]
Good catch, thank you for the contribution!
