### ISSUE TITLE
Change properties to be enumerable

### ISSUE THREAD

**Issue by manuelmager** [yury-dymov/redux-object#24]
When building an object from a normalized structure, properties that originate from a relationship in the normalized structure are non-enumerable. When iterating over the properties of the built object or when using Object.assign on it, those properties are lost.

Is there a specific reason for not using `enumerable: true` in [line 85](https://github.com/yury-dymov/redux-object/blob/db8b6d79e570ee2cb4450a2e835d3ebf4624d2fe/src/redux-object.js#L85)?

**Comment by yury-dymov** [comment]
No good reason :) Feel free to file a PR

**Comment by yury-dymov** [comment]
Fixed in v0.5.3. Thank you for your help!
