### ISSUE TITLE
Preserve type information for each object

### ISSUE THREAD

**Issue by gnapse** [yury-dymov/redux-object#30]
@yury-dymov I've found a couple of situations where it would have been useful to still have inside the object the `type` information from the jsonapi. I propose including it as a special `$type` attribute, which is guaranteed not to interfere with normal existing attributes, given that the jsonapi spec [does not allow $ as a valid character in a member name](http://jsonapi.org/format/#document-member-names-reserved-characters).

With this change in place `build` for this jsonapi object

```javascript
{
  id: '1',
  type: 'items',
  attributes: { name: 'Hello World' },
}
```

would become this:

```javascript
{
  id: '1',
  name: 'Hello World',
  $type: 'items',
}
```

Makes sense? I can make the change and submit a pull request.

**Update:** my bad, I see that there's already an option to do this. It fits me as it is, and I'll use it. But I'd argue that the use of the name `type` is not ideal. An object could perfectly have an attribute named `type`, and this option would override it. Granted, it's an edge case, but it could technically happen.

**Comment by yury-dymov** [comment]
Don't see any action items for me with respect to @apsavin comment :)

**Comment by gnapse** [comment]
Ooops sorry, my bad.
