### ISSUE TITLE
Creating new objects across subsequent (identical) calls

### ISSUE THREAD

**Issue by kjrocker** [yury-dymov/redux-object#35]
If I have something like the following:

```
const mapStateToProps = (state, ownProps) => ({ user: build(state.data, 'user', ownProps.userId) })
```

The resulting component is going to re-render at every possible opportunity, because build returns what is _technically_ a new object on any state change.

I see that there's a `cache` parameter (but assumed it was an internal used in the recursion), so perhaps this is a case of not documenting the last parameter, rather than new functionality.

**Comment by yury-dymov** [comment]
Yeah, it will, but as we are extensively using hash maps under-the-hood and taking into account that, generally speaking, in web we don't handle millions rows of data on client side, it will be never your bottleneck.

`cache` is internal implementation detail as you correctly mentioned. It doesn't preserve anything between `build` calls.

**Comment by apsavin** [comment]
It can become a bottleneck even with one row of data on a big enough page
with big enough number of connected components.

**Comment by apsavin** [comment]
You can use a caching selector for such a simple case though.

**Comment by yury-dymov** [comment]
Well, everything can become a bottleneck in a certain use-cases...
Thank you for the valuable additions: feel free to use some kind of LRU cache for this if you believe that `build` is slowing down you that much

**Comment by kjrocker** [comment]
Thank you for all this! I've worked with caching selectors before, it just skipped my mind for this use case.
