### ISSUE TITLE
Cyclical state

### ISSUE THREAD

**Issue by maharjanaman** [yury-dymov/redux-object#40]
Thanks for the great library. I'm having error `cannot process cyclical state`. I have a scenario in which a team has a coach in relationship property(based on jsonapi specification) and that coach has the same team in its relationship and the cycle continues. How do we build such a response?
Sorry if this is confusing, but this is real blocker for serializing state which redux does.

**Comment by yury-dymov** [comment]
@maharjanaman Please read README. You need to override default value of `eager` parameter
