### ISSUE TITLE
[Feat. Request] "resolved" optional?

### ISSUE THREAD

**Issue by kud** [yury-dymov/redux-object#44]
Hello,

It could sound weird to you but I'm currently using this lib for my JSON:API with json-api-normalizer, which is really useful, but I don't use redux however.

That's why I would like to know if we could remove "resolved" via an option?

Thanks!

**Comment by yury-dymov** [comment]
I can recommend a couple of options here:
1) Feel free to fork and delete this like, it's just one line. This library is very stable so chances that you will stuck behind the upstream are very slim
2) You may define util function, which under-the-hood would call redux-object and delete the resolved field from the result.

Adding option for removing "resolved" field is overkill from my perspective and both options above should do the trick

**Comment by kud** [comment]
Sounds really fair to me. Thank you for your suggestion @yury-dymov 😊
