### ISSUE TITLE
Remove the core-js dep

### ISSUE THREAD

**Issue by kud** [yury-dymov/redux-object#51]
Hello,

core-js is a bit huge and IMO not necessary anymore. Is it possible to remove it from dep?

**Comment by kud** [comment]
https://github.com/yury-dymov/redux-object/commit/6cd6c88fe97dfaa12ef1a03e220000de7e20678e

I understand a bit more why you did this. However, you should publish also the source on npm in order we don't have core-js if we use it via commonjs/esm. :)

**Comment by yury-dymov** [comment]
@kud responded in json-api-normalizer. I apologize in advance if I am missing terribly anything here. Feel free to share some article, which explains how I am supposed to do things to proper support you.

Per my understanding, you should specify in your package.json the browserlist you want to support and it should automatically pick the required portion of core-js logic, which might be 0kb if you don't want ie 11 and stuff like that
