### ISSUE TITLE
serializeObject (inverse of buildObject)

### ISSUE THREAD

**Issue by minusoneman** [yury-dymov/redux-object#6]
I'm curious how to deal with merging (redux) objects back into the store.

A typical Update action for me involves:

1. Fetch Object from Redux (buildObject)
2. Modify said Object (for example, through a form)
3. Call an API to persist the update server-side
4. On Success, merge changes back into Redux

In Step 4. I currently update the 'attributes' hash manually (I use Immutable.js, but that shouldn't matter), but I'm thinking there could be a better way.

I wouldn't mind taking a stab at extending redux-object with a serializeObject (inverse of buildObject) function, if you think it would make sense to include that functionality in the library.

Thoughts?

**Comment by KenStipek** [comment]
@minusoneman couldn't you use https://github.com/yury-dymov/json-api-normalizer to do this?

**Comment by minusoneman** [comment]
@KenStipek I'd like to update the store based on the modified object in step 2 (not the server provided JSONAPI response in step 4), since I'd like to support offline use.

**Comment by yury-dymov** [comment]
@minusoneman sounds like a common redux task: create a reducer and action, which will do whatever you need

**Comment by minusoneman** [comment]
@yury-dymov that's true, and also my approach right now. But things get a little complicated if I want to Update or Delete an object. In my reducer, if I want to delete an object, I'll:

1. Delete the object from store (simple)
2. Find all relationships to said object and remove (yuk!)

Create an object (client-side)
1. Create object manually in store
2. Create all relationships

I'm wondering if there could be a 'generic' solution to this, not unlike this approach: https://github.com/giadc/giadc-redux-json-api#manipulating-entities

**Comment by yury-dymov** [comment]
Sorry for the delayed response.

Well, I understand, what you are talking about. redux-object itself is about reading data from the store, we don't mutate anything here, so I am closing this :)

Regarding mentioned case, I find this problem in general quite hard to solve but we can brainstorm for the particular use-cases. Feel free to ping me via yury@dymov.me

**Comment by minusoneman** [comment]
Appreciate you talking your time!

I'll do some thinking as well, and get back to you if I come up with something useful.

Thanks for a neat little library.

**Comment by gnapse** [comment]
@minusoneman I see that you say you're having difficulty with step 4, but it is step three the one I'm worried about right now:

> 1. Fetch Object from Redux (buildObject)
> 2. Modify said Object (for example, through a form)
> 3. Call an API to persist the update server-side
> 4. On Success, merge changes back into Redux

When calling the api to update an object, this is done via a POST request to the object's URI, and the payload must be the payload must be the object in jsonapi format. How do you approach converting the object you received from this library's `build` function, back into the following format

```
{ id, type, attributes: { ... }, relationships: { ... } }
```

In particular I'm having trouble knowing which attributes of the non-normalized object obtained from `build` were originally relationships and which ones were regular attributes. You can see more about this trouble I'm having in #29.
