### ISSUE TITLE
Suggestion: option to eager load relationships

### ISSUE THREAD

**Issue by SirLamer** [yury-dymov/redux-object#7]
Basically, I am interested in using this in Vuex and Vue, however when Vue components read the store data in to localized computed properties, they take the raw object value at that time and don't take the lazy loader getter. Since Vue is basically caching that result, if I try to access the relationship on the computed property result it comes back as "undefined".

I can think of hacky ways to get around this (ie. touch the relationships within the computed property method just to invoke the loader) however this gets sloppy fast.

So... how about some way to force eager loading of all available relationship data in the local store at build time? Thoughts?

**Comment by yury-dymov** [comment]
@SirLamer I guess we can add new option `disableLazyLoading` or something similar to load object and relationships at once. What do you think?

**Comment by SirLamer** [comment]
In my forked copy here I added a parameter 'eager' which, when true, skips the getter creation and just retrieves the relationship value.
https://github.com/SirLamer/redux-object/blob/master/src/redux-object.js

Per our other conversation I'll submit a PR after a short period of testing.

**Comment by yury-dymov** [comment]
Closed via https://github.com/yury-dymov/redux-object/pull/9
